// Copyright 2026 M Ghiyast Farisi
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package mac implements Families 3 and 4 (MAC and MAC with IV).
// Family 3: mac(), mac_verify() — HMAC-SHA256/384/512, HMAC-SHA3-256, AES-CMAC.
// Family 4: mac_iv(), mac_iv_verify() — AES-GMAC (requires nonce).
package mac

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/sha512"
	"crypto/subtle"

	"golang.org/x/crypto/sha3"

	"github.com/moeghifar/krypton/lib/config"
	cerr "github.com/moeghifar/krypton/lib/errors"
)

// MAC algorithm identifiers.
const (
	AlgorithmHMACSHA256   = "HMAC-SHA256"
	AlgorithmHMACSHA384   = "HMAC-SHA384"
	AlgorithmHMACSHA512   = "HMAC-SHA512"
	AlgorithmHMACSHA3_256 = "HMAC-SHA3-256"
	AlgorithmAESCMAC      = "AES-CMAC"
	AlgorithmAESGMAC      = "AES-GMAC"
)

// Mac computes a message authentication code over data using key and algorithm.
// Family 3: mac(key []byte, data []byte, algorithm string) ([]byte, error)
//
// Supported algorithms: HMAC-SHA256, HMAC-SHA384, HMAC-SHA512, HMAC-SHA3-256, AES-CMAC.
func Mac(key []byte, data []byte, algorithm string) ([]byte, error) {
	if err := config.AlgorithmPermitted(algorithm); err != nil {
		return nil, err
	}

	switch algorithm {
	case AlgorithmHMACSHA256, AlgorithmHMACSHA384, AlgorithmHMACSHA512, AlgorithmHMACSHA3_256:
		return hmacTag(key, data, algorithm)
	case AlgorithmAESCMAC:
		return aesCMAC(key, data)
	default:
		return nil, cerr.ErrAlgorithmNotPermitted
	}
}

// MacVerify verifies a MAC tag using constant-time comparison.
// Family 3: mac_verify(key []byte, data []byte, tag []byte, algorithm string) (bool, error)
func MacVerify(key []byte, data []byte, tag []byte, algorithm string) (bool, error) {
	expected, err := Mac(key, data, algorithm)
	if err != nil {
		return false, err
	}
	if len(expected) != len(tag) {
		return false, nil
	}
	return subtle.ConstantTimeCompare(expected, tag) == 1, nil
}

// MacIV computes a GMAC tag and generates a nonce internally.
// Family 4: mac_iv(key []byte, data []byte, algorithm string) (tag []byte, nonce []byte, error)
//
// Only algorithm: AES-GMAC.
// nonce is 12 bytes, generated internally. Caller must store and provide nonce on verify.
func MacIV(key []byte, data []byte, algorithm string) (tag []byte, nonce []byte, err error) {
	if err := config.AlgorithmPermitted(algorithm); err != nil {
		return nil, nil, err
	}

	if algorithm != AlgorithmAESGMAC {
		return nil, nil, cerr.ErrAlgorithmNotPermitted
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, nil, cerr.ErrKeySizeInvalid
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, nil, err
	}

	nonceSize := gcm.NonceSize()
	nonce = make([]byte, nonceSize)
	if _, err := rand.Read(nonce); err != nil {
		return nil, nil, err
	}

	// GMAC: data is AAD, no plaintext. Seal output == tag.
	tag = gcm.Seal(nil, nonce, nil, data)
	return tag, nonce, nil
}

// MacIVVerify verifies a GMAC tag with the nonce that was generated by MacIV.
// Family 4: mac_iv_verify(key, data, nonce, tag, algorithm) (bool, error)
func MacIVVerify(key []byte, data []byte, nonce []byte, tag []byte, algorithm string) (bool, error) {
	if err := config.AlgorithmPermitted(algorithm); err != nil {
		return false, err
	}

	if algorithm != AlgorithmAESGMAC {
		return false, cerr.ErrAlgorithmNotPermitted
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return false, cerr.ErrKeySizeInvalid
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return false, err
	}

	// Open verifies the GMAC tag. data is AAD, tag is the ciphertext to verify.
	_, err = gcm.Open(nil, nonce, tag, data)
	return err == nil, nil
}

// hmacTag computes HMAC using the Go standard library crypto/hmac.
func hmacTag(key, data []byte, algo string) ([]byte, error) {
	switch algo {
	case AlgorithmHMACSHA256:
		mac := hmac.New(sha256.New, key)
		mac.Write(data)
		return mac.Sum(nil), nil
	case AlgorithmHMACSHA384:
		mac := hmac.New(sha512.New384, key)
		mac.Write(data)
		return mac.Sum(nil), nil
	case AlgorithmHMACSHA512:
		mac := hmac.New(sha512.New, key)
		mac.Write(data)
		return mac.Sum(nil), nil
	case AlgorithmHMACSHA3_256:
		mac := hmac.New(sha3.New256, key)
		mac.Write(data)
		return mac.Sum(nil), nil
	default:
		return nil, cerr.ErrAlgorithmNotPermitted
	}
}

// aesCMAC computes AES-CMAC per SP 800-38B.
// key must be 16, 24, or 32 bytes (AES-128/192/256).
func aesCMAC(key, data []byte) ([]byte, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, cerr.ErrKeySizeInvalid
	}
	c, err := NewCMAC(block)
	if err != nil {
		return nil, err
	}
	c.Write(data)
	return c.Sum(nil), nil
}
